/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ly_update_HotFixPlugin */

#ifndef _Included_com_ly_update_HotFixPlugin
#define _Included_com_ly_update_HotFixPlugin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ly_update_HotFixPlugin
 * Method:    Init
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ly_update_HotFixPlugin_Init
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_ly_update_HotFixPlugin
 * Method:    GetRunningCpuType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ly_update_HotFixPlugin_GetRunningCpuType
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
