/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ly_update_TestSO */

#ifndef _Included_com_ly_update_TestSO
#define _Included_com_ly_update_TestSO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ly_update_TestSO
 * Method:    Init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ly_update_HotFixPlugin_Init
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
